### ISSUE TITLE
NullPointerException Can't find properties in the Model

### ISSUE THREAD

**Issue by zombie10** [stavshamir/swagger4kafka#16]
```
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.stavshamir.swagger4kafka.services.KafkaEndpointsService]: Constructor threw exception; nested exception is java.lang.NullPointerException
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:217) ~[spring-beans-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:117) ~[spring-beans-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:310) ~[spring-beans-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	... 19 common frames omitted
Caused by: java.lang.NullPointerException: null
	at com.stavshamir.swagger4kafka.services.ModelsService.getEnumProperties(ModelsService.java:89) ~[swagger4kafka-1.0.0.jar:na]
	at com.stavshamir.swagger4kafka.services.ModelsService.setDeserializableEnumValues(ModelsService.java:84) ~[swagger4kafka-1.0.0.jar:na]
	at com.stavshamir.swagger4kafka.services.ModelsService.setDeserializableEnumValues(ModelsService.java:63) ~[swagger4kafka-1.0.0.jar:na]
	at com.stavshamir.swagger4kafka.services.ModelsService.register(ModelsService.java:51) ~[swagger4kafka-1.0.0.jar:na]
	at com.stavshamir.swagger4kafka.services.KafkaListenersScanner.topicToEndpoint(KafkaListenersScanner.java:65) ~[swagger4kafka-1.0.0.jar:na]
	at com.stavshamir.swagger4kafka.services.KafkaListenersScanner.lambda$createKafkaEndpoints$2(KafkaListenersScanner.java:48) ~[swagger4kafka-1.0.0.jar:na]
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195) ~[na:na]
```

Version used:

```
 <dependency>
            <groupId>com.stavshamir</groupId>
            <artifactId>swagger4kafka</artifactId>
            <version>1.0.0</version>
        </dependency>
        <dependency>
            <groupId>com.stavshamir</groupId>
            <artifactId>swagger4kafka-ui</artifactId>
            <version>1.0.0</version>
        </dependency>

```

Springboot version:

```
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.2.6.RELEASE</version>
        <relativePath/> <!-- lookup parent from repository -->
    </parent>
```

**Comment by stavshamir** [comment]
Thanks for reporting the issues. It looks like you are using an old version from the time I was experimenting with publishing this library (notice the package name has changed). Please let me know if you found instructions using this version.

Please use the latest version from jcenter:
```
<dependencies>
    <dependency>
      <groupId>io.github.stavshamir</groupId>
      <artifactId>swagger4kafka</artifactId>
      <version>0.0.3</version>
    </dependency>
    <dependency>
      <groupId>io.github.stavshamir</groupId>
      <artifactId>swagger4kafka-ui</artifactId>
      <version>0.0.1</version>
    </dependency>
</dependencies>
```

If you this bug still occurs in this version, please open a new issue.
